[buildPlans.IosevkaCapy]
family = "Iosevka Capy"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCapy.variants.design]
one = "base"
six = "closed-contour"
nine = "closed-contour"
capital-g = "toothed-serifless-hooked"
capital-i = "short-serifed"
capital-q = "crossing-baseline"
a = "double-storey-serifless"
b = "toothless-rounded-serifless"
d = "toothless-rounded-serifless"
f = "flat-hook-serifless"
g = "double-storey"
i = "serifed-flat-tailed"
l = "tailed-serifed"
m = "earless-single-arch-short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
u = "toothless-corner-serifless"
w = "cursive-serifless"
y = "straight-turn-serifless"
lower-gamma = "straight"
lower-delta = "flat-top"
lower-pi = "tailless"
asterisk = "turn-hex-low"
paren = "flat-arc"
brace = "straight"
ampersand = "upper-open"
at = "compact"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
question = "corner"
lig-ltgteq = "slanted"
