---
- name: Set the Floorp Flatkpak as the default Web Browser
  become: false
  ansible.builtin.shell: "xdg-settings set default-web-browser one.ablaze.floorp.desktop"

# - name: Install Floorp dotfiles
#   ansible.builtin.shell: "cp ~/.local/share/chezmoi/other/arch/.floorp/* ~/.var/app/one.ablaze.floorp/.floorp/*release/chrome/"

- name: Set Gnome DE wallpaper
  become: true
  ansible.builtin.shell: "gsettings set org.gnome.desktop.background picture-uri file:///$HOME/Wallpapers/mountains.png"
