#!/bin/sh

gitall() {
    local message="${*:-update}"
    git add . && git commit -m "$message" && git push
}

help() {
    "$@" --help | $PAGER
}

lfcd() {
    cd "$(command lf -print-last-dir "$@")"
}

fe() {
    $EDITOR $(fd . "$@" --hidden --type file | fzf)
}

fcd() {
    cd $(fd . "$@" --hidden --type dir | fzf)
}
