#!/bin/sh

append-path() {
    local dir=$1
    case ":$PATH:" in
    *:"$dir":*) ;;
    *)
        export PATH="$dir:$PATH"
        ;;
    esac
}


## XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"


## Default Programs
export EDITOR=nvim
export VISUAL=nvim
export PAGER=nvimpager
export BROWSER=firefox
export TERMINAL=wezterm
export TERMINAL_PROG=wezterm


## ZSH
# export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/history"


## Bash
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"


## X11
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"


## GTK
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"


## Progams
# export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
#export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"


## Rust
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
append-path "$CARGO_HOME/bin"


## Go
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
append-path "$GOPATH/bin"


## Lua
export LUAROCKS_HOME="$XDG_DATA_HOME/luarocks"

export LUA_PATH="$LUA_PATH;./?.lua"
export LUA_PATH="$LUA_PATH;./?/init.lua"
export LUA_PATH="$LUA_PATH;/usr/lib/lua/5.3/?.lua"
export LUA_PATH="$LUA_PATH;/usr/share/lua/5.3/?/init.lua"
export LUA_PATH="$LUA_PATH;/usr/lib/lua/5.3/?/init.lua"
export LUA_PATH="$LUA_PATH;$LUAROCKS_HOME/share/lua/5.3/?.lua"
export LUA_PATH="$LUA_PATH;$LUAROCKS_HOME/share/lua/5.3/?/init.lua"

export LUA_CPATH="$LUA_CPATH;./?.so"
export LUA_CPATH="$LUA_CPATH;/usr/lib/lua/5.3/?.so"
export LUA_CPATH="$LUA_CPATH;/usr/lib/lua/5.3/loadall.so"
export LUA_CPATH="$LUA_CPATH;$LUAROCKS_HOME/lib/lua/5.3/?.so"


## PNPM
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
append-path "$PNPM_HOME"


## Local Binaries
export LOCAL_BIN="$HOME/.local/bin"
append-path "$LOCAL_BIN"
for dir in "$LOCAL_BIN"/*; do
    [ -d "$dir" ] && append-path "$dir"
done
unset dir


## WSL
# Sometimes, it is necessary to update and install WSL2 and WSLG manually.
if grep -qi microsoft /proc/version; then
    export DISPLAY=:0
    export BROWSER="wslview"
fi


unset -f append-path
