[colorscheme]
name = "catppuccin"
flavor = "mocha"
dark_flavor = "mocha"
light_flavor = "frappe"
accent = "mauve"

[font]
size = 11
name = "IosevkaCapy Nerd Font"
path = "~/.local/share/fonts"

[windows.scoop]
buckets = ["extras", "nerd-fonts", "games", "versions"]

packages.cli = [
    "aria2",
    "chezmoi",
    "direnv",
    "neovim",
    "pwsh",
    "dark",
    "ripgrep",
    "fd",
    "jq",
    "less",
    "fzf",
    "sed",
    "yazi",
    "sudo",
    "git",
    "gh",
    "lazygit",
    "starship",
    "psreadline",
    "z",
    "bat",
    "rktools2k3",
]

packages.prog_langs = [
    "gcc",
    "tree-sitter", # for neovim latex parser
    "vcpkg",
    "cmake",
    "ninja",
    "python",
    "lua",
    "luarocks",
    "luajit",
    "nodejs",
    "pnpm",
    "stack",
]

packages.fonts = ["Hack-NF", "ZedMono-NF"]

packages.gui = [
    "vscode",
    "freedownloadmanager",
    "sysinternals",
    "vlc",
    "alacritty",
    "wezterm",
    "powertoys",
    "discord",
    "firefox",
    "sublime-text",
    "steam",
    "obsidian",
    "screentogif",
    "spicetify-cli",
    "7zip",
]
