---
rpm_packages:
  - input-remapper
  - ulauncher
  - dbus-x11

  - alacritty
  - git
  - gh
  - wget
  - ranger
  - zoxide
  - neovim
  - tmux
  - htop
  - neofetch

  - unzip
  - fzf
  - autoconf
  - ripgrep
  - direnv
  - sed
  - fd
  - findutils
  - make

  - firefox
  - rclone
  - libreoffice

  - imv
  - zathura
  - zathura-pdf-mupdf

  - gcc

  - lua
  - luarocks

  - nodejs
  - npm
  - pnpm

  - python3
  - python3-pip
  - python3-numpy
  - python3-scipy
  - python3-pandas
  - python3-matplotlib
  - python3-ipython

  - golang

  - rustup

  - starship
  - lazygit
