---
- name: Enable system services
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    scope: system
    name: "{{ item }}"
  loop: "{{ system_services }}"
  tags: services.system
# - name: Enable user services
#   become: false
#   ansible.builtin.systemd:
#     state: started
#     enabled: true
#     scope: user
#     name: "{{ item }}"
#   loop: "{{ user_services }}"
#   tags: services.user
