[buildPlans.IosevkaCustom]
family = "Iosevka Capy"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaCustom.variants]
inherits = "ss14"

[buildPlans.IosevkaCustom.variants.design]
three = "flat-top-serifless"
six = "closed-contour"
seven = "straight-serifed"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "tall-slashed"
capital-b = "standard-serifless"
capital-g = "toothed-serifless-hooked"
capital-j = "serifed"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing-baseline"
capital-r = "straight-serifless"
a = "double-storey-serifless"
f = "flat-hook-serifless"
g = "double-storey-open"
i = "serifed-flat-tailed"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-corner-serifless"
w = "straight-flat-top-serifless"
x = "straight-bilateral-motion-serifed"
y = "cursive-serifless"
z = "straight-serifed-with-horizontal-crossbar"
lower-alpha = "crossing"
lower-gamma = "straight"
lower-nu = "casual"
lower-pi = "tailless"
lower-upsilon = "casual-serifless"
asterisk = "turn-hex-low"
at = "compact"
dollar = "open"
cent = "open"
question = "corner"
lig-ltgteq = "flat"
lig-neq = "more-slanted"
