---
- name: User environment setup
  hosts: localhost
  gather_facts: true
  # vars:

  tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - name: Install packages with dnf
      become: true
      ansible.builtin.dnf:
        name:
          - git
          - lazygit
          - github-cli
          - wget

          - alacritty
          - yazi
          - zoxide
          - starship
          - neovim
          - tmux
          - htop
          - neofetch

          - unzip
          - fzf
          - autoconf
          - ripgrep
          - direnv
          - sed
          - fd
          - findutils
          - make

          - flatpak
          - firefox
          - discord
          - obsidian
          - rclone
          - libreoffice-fresh

          - imv
          - zathura
          - zathura-pdf-mupdf

          - gcc

          - lua
          - luarocks

          - nodejs
          - npm
          - pnpm

          - python
          - python-pip
          - python-numpy
          - python-scipy
          - python-pandas
          - python-matplotlib
          - ipython

          - go

          - rustup
        state: present

    - name: Ensure fonts directory
      ansible.builtin.file:
        path: "~{{ remote_regular_user }}/.local/share/fonts"
        state: directory
        mode: "0755"
        owner: "{{ remote_regular_user }}"

    - name: Check if FantasqueSans Mono exists
      ansible.builtin.shell: "ls ~{{ remote_regular_user }}/.local/share/fonts/FantasqueSans*FontMono*"
      register: fantasquesans_mono_exists
      ignore_errors: true
      changed_when: false

    - name: Download FantasqueSans mono
      when: fantasquesans_mono_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FantasqueSansMono.zip
        dest: "~{{ remote_regular_user }}/.fonts/"
        remote_src: true
        mode: "0755"
        owner: "{{ remote_regular_user }}"

    # - name: copr or fusion or user packages

    # - name: install xremap
    # - name: xremap service
    #   when: systemd
    #   ansible.builtin.service:
    #     name: xremap
    #     state: started

    # - name: install distrobox the linux wsl for arch and deb
    # https://github.com/89luca89/distrobox?tab=readme-ov-file
