---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: Install packages
      ansible.builtin.import_role:
        name: packages
      become: true
      tags: packages

    - name: Install flatpak packages
      ansible.builtin.import_role:
        name: flatpak
      become: true
      tags: flatpak

    - name: Configure desktop environment
      ansible.builtin.import_role:
        name: desktop
      become: false
      tags: desktop

    - name: Enable services
      ansible.builtin.import_role:
        name: services
      tags: services
