"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = 'gruvbox_dark'

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[\$](blue)'
vimcmd_visual_symbol = '[\$](purple)'
vimcmd_replace_one_symbol = '[\$](red)'
vimcmd_replace_symbol = '[\$](red)'

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[$user]($style) in '

## Colorschemes
[palettes.gruvbox_dark]
fg0 = '#fbf1c7'
bg1 = '#3c3836'
bg3 = '#665c54'

red = '#cc241d'
green = '#98971a'
blue = '#458588'

yellow = '#d79921'
purple = '#b16286'
orange = '#d65d0e'
aqua = '#689d6a'
