---
- name: Install packages
  ansible.builtin.dnf:
    state: present
    skip_broken: true
    allowerasing: true
    name: "{{ rpm_packages }}"

- name: Autoremove unneeded packages
  ansible.builtin.dnf:
    autoremove: true
